### ISSUE TITLE
All cars disappearing from individual stations upon return

### ISSUE THREAD

**Issue by jamesjonesphoenix** [Banjobeni/DerailValley-PersistentJobs#14]
I've twice encountered a situation where I revisit a station I've done jobs at and all the freight cars have disappeared.

It first happened at Iron Mine West which I dismissed as a freak occurrence. I reloaded a previous save from IMW and the cars didn't disappear again when revisiting the station. 

I've now noticed it happening at Harbour. All cars gone. Including cars that spawned which I didn't touch at all. 

These both happened in the same game where I started with the PJ mod from the beginning. However I started a couple days before 3.1.0 released by downloading the raw files from Github and building from source. I then updated to 3.1.0 when that released. There were only a couple more git commits between install from source and update. 

Let me know if there's any more detail I can provide.

**Comment by Banjobeni** [comment]
Hi! Thank you for the detailed problem report. I am sorry to read that you are having trouble. It is good that you started a new game with PJ enabled from the start - that rules out many cornercases already.

PJ deactivates itself if it encounters an exception. The game will then be more or less vanilla again. This could explain your observations.

In order to find out why, I need your Player.log file from right after you encounter what you describe. The game overwrites the logfile on restart, so if you've restarted the game since, we need to have it occur again.

You can also find me on Altfuture Discord.

**Comment by jamesjonesphoenix** [comment]
Roger that. Would you prefer me to post here or Discord? Either is fine with me. 

Uploaded Player.log. I loaded my last manual save at the sawmill and then quick traveled to Harbour using the map. Walked around a bit to confirm all the cars are gone and then quit the game. 

[Player.log](https://github.com/Banjobeni/DerailValley-PersistentJobs/files/12782846/Player.log)

It had been several hours of gametime since I was at the Harbour. When I was there I did a bunch of shunting jobs. Went up to Steve's garage to grab the slug. Then went back to Harbour, took a couple of freight jobs for Machine Factory and pulled them there. Since then I've been to and through a fair few other stations. 

I mention all that because just to point out it takes more than just leaving and coming back to a station to trigger this bug. I'd been away more than 2 hours from both Harbour and Iron Mine West when everything despawned so the 2 hour limit may play some part in the bug.  

Other mods I'm running: Skin Manager, Numbered Locos, Vanilla Numbered Skins, Discreet Info Plates, Booklet Organiser.

Love this mod btw, helps a lot with immersion- thanks for making it!

**Comment by Banjobeni** [comment]
Thank you for taking the time to check your savegame and upload the Player.log. However, I cannot see any exception that would originate from PJ.

I may not have been specific enough before. What we need is a Player.log where the problem actually occurs. I guess in your savegame there already weren't any cars at HB and then that did't change when you travelled to HB. But the bug most likely occurred way before that, then you saved, closed the game, and when you started and loaded the savegame as of today, you saw the effect, but not the cause, and thus there is no hint in the log files

I know it may be rather hard to pinpoint it exactly if/when it happens. I'd suggest you reach out to me on discord and we can discuss options?

By the way, there is a console command (they all start with PJ.) To clear the station spawn flag. This way, you can at least make cars spawn again in HB (execute the command and re-enter HB) and not lose youre other progress in the save.

Many thanks for your praise, love it when people love the mod and it helps me stay motivated!

**Comment by jamesjonesphoenix** [comment]
No worries and thanks for the advice on that console command, just tried it.

I just DMed you on Discord. Yes this will be tricky to pinpoint.

**Comment by jamesjonesphoenix** [comment]
I reckon it's past time to close this. I've never been able to replicate this issue again after many hours of gameplay including trying to purposely leave cars in dodgy places halfway out of stations or switches.

**Comment by Banjobeni** [comment]
Hi James! Many thanks for trying to replicate this bug and deciding it's time to close it. Also, PJ has gone some steps since then, maybe it's just not reproducible anymore.
