### ISSUE TITLE
Goods Factory & Town - Unload Job too long

### ISSUE THREAD

**Issue by SlendyMcTendies** [Banjobeni/DerailValley-PersistentJobs#20]
The job chain asks for an Unload job of 12 cars, which is too long for the Goods Factory

**Comment by Banjobeni** [comment]
Hi, can you please give screenshots of the job and the train situation on the loading track. In case you didn't know, it is not required that the train fits betwen the signs. it can be a bit longer than that and it still works.

**Comment by SlendyMcTendies** [comment]
Unfortunately I already deleted the job. If it's still there I'll show you the job file or consist. It's much bigger than the loading area and extends past the switches on either end. The Goods Factory loading area is probably the strictest in the game from all the ones I've seen.

**Comment by Banjobeni** [comment]
Ultimately, what I need to know is:
- at which (source) station did this job generate
- is that a job initially created when visiting that station for the first time - or - are those waggons originate from another FH/LH and being reassigned to this job
- the number and type of the waggons
- ideally, the log file of the game session where this job was generated

12 waggons does indeed sound way too long. but length checks of the loading track should be included everywhere already, so i need more info to debug this further.

I'll close this issue as not reproducible. If you observe that problem with another job, can you please open a new issue with more details? thx!

**Comment by SlendyMcTendies** [comment]
I can't remember off hand which station it generated at. However, there was a logistical haul of 4 cars that I brought to Harbor, then it combined with 8 flatbed cars as a Shunt Load of Cars and Tools, then as a Freight Haul to Goods Factory, and finally Shunt Unload at Goods Factory.

[SlendyMcTendies DV Log Nov 24 2024.log](https://github.com/user-attachments/files/17893288/SlendyMcTendies.DV.Log.Nov.24.2024.log)

**Comment by Banjobeni** [comment]
I'll reopen this as we've reproduced it and a fix is incoming that will reference this issue.

**Comment by Banjobeni** [comment]
I'll reopen this as we've reproduced it and a fix is incoming that will reference this issue.
