### ISSUE TITLE
Job card disappeared, cars no longer assigned after attempting to validate

### ISSUE THREAD

**Issue by Jomkaa** [Banjobeni/DerailValley-PersistentJobs#6]
~~During a shunting job, after parking my train on the loading track (as the job cards want you to), looking to save myself the hassle of having to uncouple everything and applying the handbrakes before moving the cars to another track, i attempted to validate the order with the cars still attached to the locomotive. Validation failed, so I went back and applied the handbrake to one of the cars. When I tried to validate again, the job card disappeared, and according to the Heads Up Display-mod, the cars are no longer assigned to a job. The reprint button on the order-machine does nothing.~~

I tried to reproduce the issue, but this time the machine correctly paid out when i validated (handbrake applied, still coupled to locomotive), so i guess you can just disregard this.

**Comment by Jomkaa** [comment]
I just had another job card dissapear after failing to validate, so it seems like there is something strange going on.

**Comment by Banjobeni** [comment]
The failing to validate was not related to this bug, that should be fixed now and will be in the next release.
