### ISSUE TITLE
Chain Jobs generated while in station do not target the entire original consist.

### ISSUE THREAD

**Issue by ben-vanderlinde** [Banjobeni/DerailValley-PersistentJobs#8]
Chain jobs such as SU jobs generated after a FH job, often don't target the entire consist. This seems to happen only for jobs are generated while still in the station.
![20230910073547_1](https://github.com/Banjobeni/DerailValley-PersistentJobs/assets/71764990/ed6ae19a-9fba-4f77-ad90-39df1bc7af70)

In the provided example save their is a 4 car consist in GF D5I which was originally a FH job from HB. 
A job GF-SU-45 has generated for 2/4 cars of the original consist, while the remaining cars in the consist are jobless.

A Subsequent job will eventually generate for the jobless cars (or immediately upon leaving the station).

This behaviour doesn't just affect FH -> SU, but I have also seen it affect SU -> LH & SL -> FH.

Typically the first job spawned seems to only take exactly half the original consist.

For shorter consists (eg the example of 4 cars), you generally end up with 2 jobs.

For longer consists (eg 10 cars), I have observed the splitting behaviour degrade on subsequent generations to shorter consists. That is a 10 car consist may split in to 4 jobs of 5cars, 1 car, 2 cars, 2 cars.
[00017_2023-09-10_07_38_45.zip](https://github.com/Banjobeni/DerailValley-PersistentJobs/files/12566775/00017_2023-09-10_07_38_45.zip)

**Comment by ben-vanderlinde** [comment]
After building the latest from sources, this behaviour appears to have been resolved perhaps by the fix for #2

**Comment by Banjobeni** [comment]
Great, thanks for testing with the latest sources! Reach me on altfuture discord if you'd like to test new changes more frequently.
